In [1]:
import pandas as pd

In [2]:
#Series de pandas
numeros = [3,4,5,6,7]
serie = pd.Series(numeros)
serie, type(serie)

(0    3
 1    4
 2    5
 3    6
 4    7
 dtype: int64,
 pandas.core.series.Series)

In [3]:
data = {
    "Nombre" : ["Ana", "Pedro", "Maria", "Luis", "Juan"],
    "Edad" : [22,25,34,21,28],
    "Ciudad": ["Sonsonate", "Santa Ana", "San Salvador","San Miguel", "Usulutan"]
}

data, type(data)

({'Nombre': ['Ana', 'Pedro', 'Maria', 'Luis', 'Juan'],
  'Edad': [22, 25, 34, 21, 28],
  'Ciudad': ['Sonsonate',
   'Santa Ana',
   'San Salvador',
   'San Miguel',
   'Usulutan']},
 dict)

In [4]:
#Generar un DataFrame apartir de un diccionario

df = pd.DataFrame(data=data)

df

Nombre  Edad        Ciudad
0    Ana    22     Sonsonate
1  Pedro    25     Santa Ana
2  Maria    34  San Salvador
3   Luis    21    San Miguel
4   Juan    28      Usulutan

In [5]:
# exportar DataFrame

df.to_csv("data.csv")

In [6]:
# importar un DataFrame

import_df = pd.read_csv("data.csv", index_col=0)
import_df

Nombre  Edad        Ciudad
0    Ana    22     Sonsonate
1  Pedro    25     Santa Ana
2  Maria    34  San Salvador
3   Luis    21    San Miguel
4   Juan    28      Usulutan

In [7]:
nombres = df["Nombre"]
print(nombres, type(nombres))

0      Ana
1    Pedro
2    Maria
3     Luis
4     Juan
Name: Nombre, dtype: object <class 'pandas.core.series.Series'>


In [8]:
# Seleccionar una o mas columnas
df = pd.DataFrame(data=data)
df[["Nombre","Edad"]]
#print(type(df))

Nombre  Edad
0    Ana    22
1  Pedro    25
2  Maria    34
3   Luis    21
4   Juan    28

In [9]:
# filtrar por indice
fila = df.loc[2]
fila

Nombre           Maria
Edad                34
Ciudad    San Salvador
Name: 2, dtype: object

In [10]:
#filtrar por condiciones
df [df['Edad']>23]

Nombre  Edad        Ciudad
1  Pedro    25     Santa Ana
2  Maria    34  San Salvador
4   Juan    28      Usulutan

In [11]:
#filtrar por dos condiciones
filtro = (df['Edad']>23) & (df['Nombre'].str.startswith('P'))
df[filtro]

Nombre  Edad     Ciudad
1  Pedro    25  Santa Ana

In [12]:
#filtrar por query
df.query('Edad < 23')

Nombre  Edad      Ciudad
0    Ana    22   Sonsonate
3   Luis    21  San Miguel

In [13]:
# extraer nombres especificos
df[df['Nombre'].isin(['Ana','Carlos','Juan'])]

Nombre  Edad     Ciudad
0    Ana    22  Sonsonate
4   Juan    28   Usulutan

In [14]:
#filtro usando funcion
def longitud_5(nombre):
    return len(nombre) == 5
df[df['Nombre'].apply(longitud_5)] 

Nombre  Edad        Ciudad
1  Pedro    25     Santa Ana
2  Maria    34  San Salvador

In [15]:
#filtrar por edades entre 25 y 35 (inclusive)
df[df['Edad'].between(25,35)]

Nombre  Edad        Ciudad
1  Pedro    25     Santa Ana
2  Maria    34  San Salvador
4   Juan    28      Usulutan

In [16]:
import numpy as np


In [17]:
data = {
    "Nombre" : ["Ana", "Pedro", "Maria", "Luis", "Juan"],
    "Edad" : [22,25,np.nan,21,28],
    "Ciudad": ["Sonsonate", "Santa Ana", "San Salvador",None, "Usulutan"]
}
df = pd.DataFrame(data)
df

Nombre  Edad        Ciudad
0    Ana  22.0     Sonsonate
1  Pedro  25.0     Santa Ana
2  Maria   NaN  San Salvador
3   Luis  21.0          None
4   Juan  28.0      Usulutan

In [18]:
#Rellenar los valores faltantes
df_fill = df.fillna(
    {
        'Edad' : df['Edad'].mean(), # si el valor de la edad es nulo lo reemplaza por la edad promedio
        'Ciudad' : 'Desconocido'
    }
)
df_fill 

Nombre  Edad        Ciudad
0    Ana  22.0     Sonsonate
1  Pedro  25.0     Santa Ana
2  Maria  24.0  San Salvador
3   Luis  21.0   Desconocido
4   Juan  28.0      Usulutan

In [19]:
#eliminacion de fila con valores faltantes
df_sin_nan = df.dropna()
df_sin_nan

Nombre  Edad     Ciudad
0    Ana  22.0  Sonsonate
1  Pedro  25.0  Santa Ana
4   Juan  28.0   Usulutan

In [20]:
#reemplazar valores especificos de alguna columna
df_reem = df.replace(
    {
        "Ciudad" : {None : 'Desconocido'}
    }
)
df_reem

Nombre  Edad        Ciudad
0    Ana  22.0     Sonsonate
1  Pedro  25.0     Santa Ana
2  Maria   NaN  San Salvador
3   Luis  21.0   Desconocido
4   Juan  28.0      Usulutan

In [21]:
# Interpolar valores
df_interpolado = df.copy()
df_interpolado['Edad'] = df['Edad'].interpolate()
df_interpolado

Nombre  Edad        Ciudad
0    Ana  22.0     Sonsonate
1  Pedro  25.0     Santa Ana
2  Maria  23.0  San Salvador
3   Luis  21.0          None
4   Juan  28.0      Usulutan

In [22]:
data_duplicada = {
    "Nombre" : ["Ana", "Pedro", "Maria", "Luis", "Juan","Ana","Pedro"],
    "Edad" : [22,25,np.nan,21,28,22,25],
    "Ciudad": ["Sonsonate", "Santa Ana", "San Salvador",None, "Usulutan","Sonsonate","Santa Ana"]
}
df_duplicado = pd.DataFrame(data_duplicada)
df_duplicado

Nombre  Edad        Ciudad
0    Ana  22.0     Sonsonate
1  Pedro  25.0     Santa Ana
2  Maria   NaN  San Salvador
3   Luis  21.0          None
4   Juan  28.0      Usulutan
5    Ana  22.0     Sonsonate
6  Pedro  25.0     Santa Ana

In [23]:
# eliminar elementos duplicados
df_sin_duplicado = df_duplicado.drop_duplicates()
df_sin_duplicado

Nombre  Edad        Ciudad
0    Ana  22.0     Sonsonate
1  Pedro  25.0     Santa Ana
2  Maria   NaN  San Salvador
3   Luis  21.0          None
4   Juan  28.0      Usulutan

In [24]:
# renombrar columnas 
df_renombrado = df.rename(
    columns={
        "Nombre" : "Name",
        "Edad" : "Age",
        "Ciudad" : "City"
    }
)
df_renombrado

Name   Age          City
0    Ana  22.0     Sonsonate
1  Pedro  25.0     Santa Ana
2  Maria   NaN  San Salvador
3   Luis  21.0          None
4   Juan  28.0      Usulutan

In [25]:
# ordenar columnas
columnas_ordenadas = ["Ciudad","Edad","Nombre"]
df_ordenado = df[columnas_ordenadas]
df_ordenado

Ciudad  Edad Nombre
0     Sonsonate  22.0    Ana
1     Santa Ana  25.0  Pedro
2  San Salvador   NaN  Maria
3          None  21.0   Luis
4      Usulutan  28.0   Juan

In [26]:
# transformacion de datos
def cuadrado(x):
    return x**2

df["Edad_cuadrado"] = df["Edad"].apply(cuadrado)
df

Nombre  Edad        Ciudad  Edad_cuadrado
0    Ana  22.0     Sonsonate          484.0
1  Pedro  25.0     Santa Ana          625.0
2  Maria   NaN  San Salvador            NaN
3   Luis  21.0          None          441.0
4   Juan  28.0      Usulutan          784.0

In [27]:
# agrupacion de datos
data = {'Nombre': ['Juan','Ana','Luis','Laura','Pedro','Carla'],
        'Ciudad': ['Madrid','Barcelona','Madrid','Valencia','Barcelona','Madrid'],
        'Edad': [25,33,30,28,45,38],
        'Puntuacion': [80,90,85,88,75,91]

}
df = pd.DataFrame(data)
df

Nombre     Ciudad  Edad  Puntuacion
0   Juan     Madrid    25          80
1    Ana  Barcelona    33          90
2   Luis     Madrid    30          85
3  Laura   Valencia    28          88
4  Pedro  Barcelona    45          75
5  Carla     Madrid    38          91

In [28]:
# agrupar por ciudad
grouped = df.groupby('Ciudad')
print(grouped.groups)

{'Barcelona': [1, 4], 'Madrid': [0, 2, 5], 'Valencia': [3]}


In [29]:
# Calcular la suma de las edades y puntuaciones por ciudad
aggregated_data = grouped.agg(
    {
        "Edad" : "mean",
        "Puntuacion" : "sum"
    }
)
aggregated_data 

Edad  Puntuacion
Ciudad                     
Barcelona  39.0         165
Madrid     31.0         256
Valencia   28.0          88

In [30]:
# definir funcion de agregacion personalizada
def rango(series):
    return series.max() - series.min()

# Aplicar la funcion agg pesonalizada al grupo
aggregated_data_custom = grouped.agg(
    {
        "Edad" : rango,
        "Puntuacion" : rango
    }
)
aggregated_data_custom 

Edad  Puntuacion
Ciudad                     
Barcelona    12          15
Madrid       13          11
Valencia      0           0

In [31]:
data["Categoria"] = ["A","B","A","B","A","B"]
df = pd.DataFrame(data)
df

Nombre     Ciudad  Edad  Puntuacion Categoria
0   Juan     Madrid    25          80         A
1    Ana  Barcelona    33          90         B
2   Luis     Madrid    30          85         A
3  Laura   Valencia    28          88         B
4  Pedro  Barcelona    45          75         A
5  Carla     Madrid    38          91         B

In [32]:
# Agrupar datos por ciudad y categoria
grouped_multi = df.groupby(['Ciudad', 'Categoria'])
grouped_multi.groups

{('Barcelona', 'A'): [4], ('Barcelona', 'B'): [1], ('Madrid', 'A'): [0, 2], ('Madrid', 'B'): [5], ('Valencia', 'B'): [3]}

In [33]:
# Calcular la suma de las edades y puntuacion por ciudad y por categoria
aggregated_data_multi = grouped_multi.agg(
    {
        "Edad" : "sum",
        "Puntuacion" : "mean"
    }
)
aggregated_data_multi

Edad  Puntuacion
Ciudad    Categoria                  
Barcelona A            45        75.0
          B            33        90.0
Madrid    A            55        82.5
          B            38        91.0
Valencia  B            28        88.0

In [34]:
# Agregar una columna 
# Crear una DataFrame de ejemplo
data = {'Nombre': ['Juan', 'Pedro','Ana','Luis'],
        'Edad': [25,33,30,28]}
df = pd.DataFrame(data)
df

Nombre  Edad
0   Juan    25
1  Pedro    33
2    Ana    30
3   Luis    28

In [35]:
# Agregar una columna 
df["Ciudad"] = ["Sonsonate", "Santa Ana", "Sonsonate", "San Salvador"]
df

Nombre  Edad        Ciudad
0   Juan    25     Sonsonate
1  Pedro    33     Santa Ana
2    Ana    30     Sonsonate
3   Luis    28  San Salvador

In [36]:
# Generamos una nueva fila 
new_row = pd.Series({"Nombre": "Luis", "Edad": 34, "Ciudad": "San Miguel"})

# Agregamos fila al DataFrame  (el panda series se convierte a Dataframe)
df = pd.concat([df,new_row.to_frame().T], ignore_index=True)
df

Nombre Edad        Ciudad
0   Juan   25     Sonsonate
1  Pedro   33     Santa Ana
2    Ana   30     Sonsonate
3   Luis   28  San Salvador
4   Luis   34    San Miguel

In [37]:
data = {'Nombre': ['Juan', 'Pedro','Ana','Luis'],
        'Edad': [25,33,30,28]}
df1 = pd.DataFrame(data)
df1["Ciudad"] = ["Sonsonate", "Santa Ana", "Sonsonate", "San Salvador"]
df1	
# Creamos otro DataFrame de ejemplo

data2 = {'Nombre': ['Karla', 'Irene'],
         'Edad' : [38,27],
         'Ciudad' : ['Sonsonate','La Libertad']}
df2 = pd.DataFrame(data2)

df1

Nombre  Edad        Ciudad
0   Juan    25     Sonsonate
1  Pedro    33     Santa Ana
2    Ana    30     Sonsonate
3   Luis    28  San Salvador

In [38]:
df2

Nombre  Edad       Ciudad
0  Karla    38    Sonsonate
1  Irene    27  La Libertad

In [39]:
# Combinar dos Dataframe
df_combined = pd.concat([df1,df2], ignore_index=True)
df_combined

Nombre  Edad        Ciudad
0   Juan    25     Sonsonate
1  Pedro    33     Santa Ana
2    Ana    30     Sonsonate
3   Luis    28  San Salvador
4  Karla    38     Sonsonate
5  Irene    27   La Libertad

In [40]:
import numpy as np

In [41]:
# Crear un arreglo con 5 elementos
arr1 = np.array([1,2,3,4,5,6])

print("Arreglo 1D: ", arr1)
print("Forma(shape): ", arr1.shape)
print("Tipo de datos(dtype) ", arr1.dtype)

Arreglo 1D:  [1 2 3 4 5 6]
Forma(shape):  (6,)
Tipo de datos(dtype)  int64


In [42]:
# Cambiar el arreglo por una matriz de 2x3
arr2 = arr1.reshape((2,3))
print("Arreglo 2D:\n ", arr2)
print("Forma(shape): ", arr2.shape)
print("Tipo de datos(dtype) ", arr2.dtype)

Arreglo 2D:
  [[1 2 3]
 [4 5 6]]
Forma(shape):  (2, 3)
Tipo de datos(dtype)  int64


In [43]:
# Crear una matriz con forma (4,4) con numeros aleatorios entre 0 y 1
matrix = np.random.rand(4,4)
print("Arreglo 2D:\n ", matrix)
print("Forma(shape): ", matrix.shape)
print("Tipo de datos(dtype) ", matrix.dtype)

Arreglo 2D:
  [[0.91109832 0.94743074 0.03600175 0.66715303]
 [0.73393785 0.09878633 0.06474711 0.42938768]
 [0.86562674 0.40659983 0.25915062 0.67100644]
 [0.82634013 0.06121895 0.36756085 0.51667889]]
Forma(shape):  (4, 4)
Tipo de datos(dtype)  float64


In [44]:
# Crear una arreglo de 2 dim a partir de una lista de listas
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr, type(arr)) 

[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'>


In [46]:
# Crear una arreglo de ceros con una forma (3,4)
arr = np.zeros((3,4))
print(arr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [47]:
# Crear arreglo con unos de la forma (2,2)
arr = np.ones((2,2))
arr[1,1]=10
print(arr)

[[ 1.  1.]
 [ 1. 10.]]


In [48]:
# Crear una matriz identidad (la misma cantidad de filas como columnas)
arr = np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [51]:
# Crear un arreglo 3D de ceros de forma (2,3,4)
arr = np.zeros((2,3,4))
arr[0,1,2] = 5
print(arr)

[[[0. 0. 0. 0.]
  [0. 0. 5. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [52]:
arr = np.random.rand(2,5)
arr

array([[0.63588184, 0.87543345, 0.77164475, 0.94278293, 0.56383775],
       [0.72685214, 0.37354689, 0.35949355, 0.56044232, 0.71248889]])

In [53]:
arr.T  #arreglo transpuesto

array([[0.63588184, 0.72685214],
       [0.87543345, 0.37354689],
       [0.77164475, 0.35949355],
       [0.94278293, 0.56044232],
       [0.56383775, 0.71248889]])

In [54]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])
arr1 , arr2

(array([[1, 2],
        [3, 4]]),
 array([[5, 6],
        [7, 8]]))

In [55]:
# concatenar arreglos horizontalmente
arr_h = np.hstack((arr1,arr2))
arr_h

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [56]:
# concatenar arreglos verticalmente
arr_v = np.vstack((arr1,arr2))
arr_v

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])